In [244]:
import numpy as np

In [245]:
import pandas as pd

In [246]:
pwd

'/Users/michael/thesis2.0/ipythes'

In [247]:
ls

All_WT_for_coopfit_tsv.csv  krinkle.ipynb
Multifit Exampls.ipynb      ligmods.py
__pycache__/                minfuncs.py
emcee site example.ipynb    mult_obj.py
emcee_lmfit_ex.ipynb        multifit.py
finally_making_sense.ipynb  objfun.py
klotzfitter.py              panders.ipynb


In [248]:
df = pd.DataFrame.from_csv('All_WT_for_coopfit_tsv.csv', sep='\t')

In [249]:
df

24k       43k       92k  120k  231k  447k  20K  46K  187K  \
[egf]                                                                       
0.007969   0.046039       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.014993   0.073019       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.030995   0.111563       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.061095   0.192505       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.095149   0.242612       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.143965   0.346681       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.243969   0.441114       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.394505   0.506638       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.686923   0.714775       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.079399   0.813062       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.847583   0.853533       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.618645   0.890150       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
4.197115   0.899786       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
8.121298   0.946039       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
16.013240  0.996146       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.008435        NaN  0.030621       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.016325        NaN  0.059529       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.032193        NaN  0.096146       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.065900        NaN  0.173233       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.097893        NaN  0.231049       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.149518        NaN  0.337045       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.253313        NaN  0.456531       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.397988        NaN  0.568308       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.693843        NaN  0.658886       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.831155        NaN  0.805353       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.570049        NaN  0.876659       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
5.068029        NaN  0.917131       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
8.196809        NaN  0.963383       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.010478        NaN       NaN  0.044111   NaN   NaN   NaN  NaN  NaN   NaN   
0.043951        NaN       NaN  0.103854   NaN   NaN   NaN  NaN  NaN   NaN   
...             ...       ...       ...   ...   ...   ...  ...  ...   ...   
12.688550       NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.011394        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.023292        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.050302        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.098623        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.175472        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.297586        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.557369        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.826670        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.522772        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.283661        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
3.910003        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
6.106213        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
9.179923        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
14.138340       NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.010226        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.017193        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.036900        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.051080        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.096354    

In [250]:
df.columns

Index(['24k', '43k', '92k', '120k', '231k', '447k', '20K', '46K', '187K',
       '256K', '1200K', '12k', '82k', '107k', '387k', '502k', '1600k'],
      dtype='object')

In [251]:
df.index

Float64Index([0.007969457,  0.01499326,  0.03099519,  0.06109528,  0.09514861,
                0.1439648,    0.243969,   0.3945051,    0.686923,    1.079399,
              ...
                0.1713248,   0.2796241,   0.4929926,   0.6729095,    1.361332,
                 1.965876,    3.560756,    5.559898,    7.705445,    12.27113],
             dtype='float64', name='[egf]', length=239)

In [252]:
for i in df.columns:
    print(i)

24k
43k
92k
120k
231k
447k
20K
46K
187K
256K
1200K
12k
82k
107k
387k
502k
1600k


In [253]:
df_24k = df['24k']

In [254]:
df_24k

[egf]
0.007969     0.046039
0.014993     0.073019
0.030995     0.111563
0.061095     0.192505
0.095149     0.242612
0.143965     0.346681
0.243969     0.441114
0.394505     0.506638
0.686923     0.714775
1.079399     0.813062
1.847583     0.853533
2.618645     0.890150
4.197115     0.899786
8.121298     0.946039
16.013240    0.996146
0.008435          NaN
0.016325          NaN
0.032193          NaN
0.065900          NaN
0.097893          NaN
0.149518          NaN
0.253313          NaN
0.397988          NaN
0.693843          NaN
1.831155          NaN
2.570049          NaN
5.068029          NaN
8.196809          NaN
0.010478          NaN
0.043951          NaN
               ...   
12.688550         NaN
0.011394          NaN
0.023292          NaN
0.050302          NaN
0.098623          NaN
0.175472          NaN
0.297586          NaN
0.557369          NaN
0.826670          NaN
1.522772          NaN
2.283661          NaN
3.910003          NaN
6.106213          NaN
9.179923          NaN
14.1

In [255]:
df_24k_na = df_24k.dropna()

In [256]:
df_24k_na

[egf]
0.007969     0.046039
0.014993     0.073019
0.030995     0.111563
0.061095     0.192505
0.095149     0.242612
0.143965     0.346681
0.243969     0.441114
0.394505     0.506638
0.686923     0.714775
1.079399     0.813062
1.847583     0.853533
2.618645     0.890150
4.197115     0.899786
8.121298     0.946039
16.013240    0.996146
Name: 24k, dtype: float64

In [257]:
import csv

In [258]:
f = open('All_WT_for_coopfit_tsv.csv')

In [259]:
tsv = csv.reader(f,delimiter='\t')

In [260]:
a = list(tsv)

In [261]:
a[0]

['[egf]',
 '24k',
 '43k',
 '92k',
 '120k',
 '231k',
 '447k',
 '20K',
 '46K',
 '187K',
 '256K',
 '1200K',
 '12k',
 '82k',
 '107k',
 '387k',
 '502k',
 '1600k']

In [262]:
a[0][0]

'[egf]'

In [263]:
a[1]

['0.007969457',
 '0.04603855',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [264]:
test = df_24k_na.as_matrix()

In [265]:
test

array([ 0.04603855,  0.07301927,  0.1115632 ,  0.1925054 ,  0.2426124 ,
        0.3466809 ,  0.4411135 ,  0.5066381 ,  0.7147752 ,  0.8130621 ,
        0.8535332 ,  0.8901499 ,  0.8997859 ,  0.9460385 ,  0.9961456 ])

In [266]:
df['[egf]'] = df.index

In [267]:
df

24k       43k       92k  120k  231k  447k  20K  46K  187K  \
[egf]                                                                       
0.007969   0.046039       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.014993   0.073019       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.030995   0.111563       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.061095   0.192505       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.095149   0.242612       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.143965   0.346681       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.243969   0.441114       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.394505   0.506638       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.686923   0.714775       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.079399   0.813062       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.847583   0.853533       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.618645   0.890150       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
4.197115   0.899786       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
8.121298   0.946039       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
16.013240  0.996146       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.008435        NaN  0.030621       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.016325        NaN  0.059529       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.032193        NaN  0.096146       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.065900        NaN  0.173233       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.097893        NaN  0.231049       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.149518        NaN  0.337045       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.253313        NaN  0.456531       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.397988        NaN  0.568308       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.693843        NaN  0.658886       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.831155        NaN  0.805353       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.570049        NaN  0.876659       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
5.068029        NaN  0.917131       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
8.196809        NaN  0.963383       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.010478        NaN       NaN  0.044111   NaN   NaN   NaN  NaN  NaN   NaN   
0.043951        NaN       NaN  0.103854   NaN   NaN   NaN  NaN  NaN   NaN   
...             ...       ...       ...   ...   ...   ...  ...  ...   ...   
12.688550       NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.011394        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.023292        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.050302        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.098623        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.175472        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.297586        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.557369        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.826670        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
1.522772        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
2.283661        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
3.910003        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
6.106213        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
9.179923        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
14.138340       NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.010226        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.017193        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.036900        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.051080        NaN       NaN       NaN   NaN   NaN   NaN  NaN  NaN   NaN   
0.096354    

In [268]:
f.close()

In [269]:
df = pd.DataFrame.from_csv('All_WT_for_coopfit_tsv.csv', sep='\t')

In [270]:
holder = []

In [271]:
for i in df.columns:
    holder.append(df[i])

In [272]:
holder[1]

[egf]
0.007969          NaN
0.014993          NaN
0.030995          NaN
0.061095          NaN
0.095149          NaN
0.143965          NaN
0.243969          NaN
0.394505          NaN
0.686923          NaN
1.079399          NaN
1.847583          NaN
2.618645          NaN
4.197115          NaN
8.121298          NaN
16.013240         NaN
0.008435     0.030621
0.016325     0.059529
0.032193     0.096146
0.065900     0.173233
0.097893     0.231049
0.149518     0.337045
0.253313     0.456531
0.397988     0.568308
0.693843     0.658886
1.831155     0.805353
2.570049     0.876659
5.068029     0.917131
8.196809     0.963383
0.010478          NaN
0.043951          NaN
               ...   
12.688550         NaN
0.011394          NaN
0.023292          NaN
0.050302          NaN
0.098623          NaN
0.175472          NaN
0.297586          NaN
0.557369          NaN
0.826670          NaN
1.522772          NaN
2.283661          NaN
3.910003          NaN
6.106213          NaN
9.179923          NaN
14.1

In [273]:
for i in range(len(holder)):
    holder[i] = holder[i].dropna()

In [274]:
holder[0]

[egf]
0.007969     0.046039
0.014993     0.073019
0.030995     0.111563
0.061095     0.192505
0.095149     0.242612
0.143965     0.346681
0.243969     0.441114
0.394505     0.506638
0.686923     0.714775
1.079399     0.813062
1.847583     0.853533
2.618645     0.890150
4.197115     0.899786
8.121298     0.946039
16.013240    0.996146
Name: 24k, dtype: float64

In [275]:
holder[1]

[egf]
0.008435    0.030621
0.016325    0.059529
0.032193    0.096146
0.065900    0.173233
0.097893    0.231049
0.149518    0.337045
0.253313    0.456531
0.397988    0.568308
0.693843    0.658886
1.831155    0.805353
2.570049    0.876659
5.068029    0.917131
8.196809    0.963383
Name: 43k, dtype: float64

In [276]:
xvals = []

In [277]:
for i in holder:
    xvals.append(i.index)

In [278]:
xvals

[Float64Index([0.007969457,  0.01499326,  0.03099519,  0.06109528,  0.09514861,
                 0.1439648,    0.243969,   0.3945051,    0.686923,    1.079399,
                  1.847583,    2.618645,    4.197115,    8.121298,    16.01324],
              dtype='float64', name='[egf]'),
 Float64Index([0.008435078,  0.01632461,  0.03219274,  0.06589953,  0.09789267,
                 0.1495181,   0.2533132,   0.3979881,   0.6938425,    1.831155,
                  2.570049,    5.068029,    8.196809],
              dtype='float64', name='[egf]'),
 Float64Index([0.01047828,   0.043951, 0.06717546,   0.159764,  0.2757842,
                0.4673179,  0.8378847,   1.341291,   2.295071,   3.222072,
                 5.068438,   9.992324,   16.32263],
              dtype='float64', name='[egf]'),
 Float64Index([0.06716596, 0.04394744,   0.142679,   0.237226,  0.3870431,
                0.4670442,   1.080119,   1.830193,   2.595465,   4.079464,
                 8.197306,   16.17389, 0.02105896],
  

In [279]:
type(xvals[0])

pandas.indexes.numeric.Float64Index

In [280]:
xvals2 = []

In [281]:
for i in holder:
    xvals2.append(i.index.tolist())

In [282]:
xvals2

[[0.0079694569999999992,
  0.01499326,
  0.030995189999999999,
  0.061095280000000002,
  0.095148609999999995,
  0.1439648,
  0.24396900000000002,
  0.3945051,
  0.68692299999999995,
  1.079399,
  1.8475830000000002,
  2.6186449999999999,
  4.1971150000000002,
  8.1212979999999995,
  16.01324],
 [0.0084350780000000004,
  0.01632461,
  0.032192739999999997,
  0.065899529999999998,
  0.097892670000000001,
  0.14951810000000001,
  0.25331320000000002,
  0.39798810000000001,
  0.69384250000000003,
  1.8311549999999999,
  2.570049,
  5.0680290000000001,
  8.196809],
 [0.01047828,
  0.043950999999999997,
  0.067175460000000006,
  0.15976400000000002,
  0.27578420000000003,
  0.46731790000000001,
  0.83788469999999993,
  1.341291,
  2.2950710000000001,
  3.2220720000000003,
  5.0684379999999996,
  9.992324,
  16.32263],
 [0.067165959999999997,
  0.043947439999999997,
  0.142679,
  0.23722600000000002,
  0.38704309999999997,
  0.46704420000000002,
  1.0801190000000001,
  1.830193,
  2.59546500

In [283]:
holder[1]

[egf]
0.008435    0.030621
0.016325    0.059529
0.032193    0.096146
0.065900    0.173233
0.097893    0.231049
0.149518    0.337045
0.253313    0.456531
0.397988    0.568308
0.693843    0.658886
1.831155    0.805353
2.570049    0.876659
5.068029    0.917131
8.196809    0.963383
Name: 43k, dtype: float64

In [284]:
type(holder[0])

pandas.core.series.Series

In [285]:
thing = holder[0]

In [286]:
type(thing)

pandas.core.series.Series

In [287]:
type(thing.values)

numpy.ndarray

In [288]:
yvals2 = []

In [289]:
for i in holder:
    yvals2.append(i.values)

In [290]:
yvals2

[array([ 0.04603855,  0.07301927,  0.1115632 ,  0.1925054 ,  0.2426124 ,
         0.3466809 ,  0.4411135 ,  0.5066381 ,  0.7147752 ,  0.8130621 ,
         0.8535332 ,  0.8901499 ,  0.8997859 ,  0.9460385 ,  0.9961456 ]),
 array([ 0.03062099,  0.05952891,  0.09614561,  0.1732334 ,  0.2310493 ,
         0.337045  ,  0.4565311 ,  0.5683084 ,  0.6588865 ,  0.8053533 ,
         0.8766595 ,  0.9171307 ,  0.9633833 ]),
 array([ 0.04411135,  0.1038544 ,  0.1443255 ,  0.3158458 ,  0.4507495 ,
         0.5528908 ,  0.6685225 ,  0.7957174 ,  0.8689507 ,  0.9132763 ,
         0.9094219 ,  0.9730192 ,  0.9710921 ]),
 array([ 0.1578158 ,  0.1115632 ,  0.3023555 ,  0.4141328 ,  0.5278373 ,
         0.6087794 ,  0.7494647 ,  0.8554604 ,  0.8381156 ,  0.9113491 ,
         0.9576017 ,  0.9441114 ,  0.07301927]),
 array([ 0.1501071 ,  0.1963597 ,  0.2869379 ,  0.3871521 ,  0.466167  ,
         0.5875803 ,  0.6955032 ,  0.7571734 ,  0.7995718 ,  0.9229122 ,
         0.9248394 ,  0.09421842]),
 array([ 0.0

In [291]:
yvals3 = np.array(yvals2)

In [292]:
type(yvals3)

numpy.ndarray

In [293]:
type(yvals3[0])

numpy.ndarray

In [294]:
type(yvals2)

list

In [295]:
type(xvals2)

list

In [296]:
brb = holder[0]

In [297]:
brb.index.values

array([  7.96945700e-03,   1.49932600e-02,   3.09951900e-02,
         6.10952800e-02,   9.51486100e-02,   1.43964800e-01,
         2.43969000e-01,   3.94505100e-01,   6.86923000e-01,
         1.07939900e+00,   1.84758300e+00,   2.61864500e+00,
         4.19711500e+00,   8.12129800e+00,   1.60132400e+01])

In [298]:
panel_name_list = df.columns.tolist()

In [299]:
wt_concs = []

In [300]:
for i in holder:
    wt_concs.append(i.index.values.tolist())

In [301]:
type(wt_concs)

list

In [302]:
wt_concs[0]

[0.007969457,
 0.01499326,
 0.03099519,
 0.06109528,
 0.09514861,
 0.1439648,
 0.24396900000000002,
 0.3945051,
 0.686923,
 1.079399,
 1.8475830000000002,
 2.618645,
 4.197115,
 8.121298,
 16.01324]

In [303]:
import lmfit as lft

In [304]:
assert 1==1

In [305]:
def func(a,b):
    assert a == b
    print('The values are',a,b)

In [308]:
func(1,1)

The values are 1 1


In [309]:
yvals2

[array([ 0.04603855,  0.07301927,  0.1115632 ,  0.1925054 ,  0.2426124 ,
         0.3466809 ,  0.4411135 ,  0.5066381 ,  0.7147752 ,  0.8130621 ,
         0.8535332 ,  0.8901499 ,  0.8997859 ,  0.9460385 ,  0.9961456 ]),
 array([ 0.03062099,  0.05952891,  0.09614561,  0.1732334 ,  0.2310493 ,
         0.337045  ,  0.4565311 ,  0.5683084 ,  0.6588865 ,  0.8053533 ,
         0.8766595 ,  0.9171307 ,  0.9633833 ]),
 array([ 0.04411135,  0.1038544 ,  0.1443255 ,  0.3158458 ,  0.4507495 ,
         0.5528908 ,  0.6685225 ,  0.7957174 ,  0.8689507 ,  0.9132763 ,
         0.9094219 ,  0.9730192 ,  0.9710921 ]),
 array([ 0.1578158 ,  0.1115632 ,  0.3023555 ,  0.4141328 ,  0.5278373 ,
         0.6087794 ,  0.7494647 ,  0.8554604 ,  0.8381156 ,  0.9113491 ,
         0.9576017 ,  0.9441114 ,  0.07301927]),
 array([ 0.1501071 ,  0.1963597 ,  0.2869379 ,  0.3871521 ,  0.466167  ,
         0.5875803 ,  0.6955032 ,  0.7571734 ,  0.7995718 ,  0.9229122 ,
         0.9248394 ,  0.09421842]),
 array([ 0.0

In [310]:
holder

[[egf]
 0.007969     0.046039
 0.014993     0.073019
 0.030995     0.111563
 0.061095     0.192505
 0.095149     0.242612
 0.143965     0.346681
 0.243969     0.441114
 0.394505     0.506638
 0.686923     0.714775
 1.079399     0.813062
 1.847583     0.853533
 2.618645     0.890150
 4.197115     0.899786
 8.121298     0.946039
 16.013240    0.996146
 Name: 24k, dtype: float64, [egf]
 0.008435    0.030621
 0.016325    0.059529
 0.032193    0.096146
 0.065900    0.173233
 0.097893    0.231049
 0.149518    0.337045
 0.253313    0.456531
 0.397988    0.568308
 0.693843    0.658886
 1.831155    0.805353
 2.570049    0.876659
 5.068029    0.917131
 8.196809    0.963383
 Name: 43k, dtype: float64, [egf]
 0.010478     0.044111
 0.043951     0.103854
 0.067175     0.144326
 0.159764     0.315846
 0.275784     0.450749
 0.467318     0.552891
 0.837885     0.668523
 1.341291     0.795717
 2.295071     0.868951
 3.222072     0.913276
 5.068438     0.909422
 9.992324     0.973019
 16.322630    0.97

In [311]:
free_lig = []

In [312]:
for i in holder:
    free_lig.append(i.index.tolist())

In [313]:
free_lig

[[0.0079694569999999992,
  0.01499326,
  0.030995189999999999,
  0.061095280000000002,
  0.095148609999999995,
  0.1439648,
  0.24396900000000002,
  0.3945051,
  0.68692299999999995,
  1.079399,
  1.8475830000000002,
  2.6186449999999999,
  4.1971150000000002,
  8.1212979999999995,
  16.01324],
 [0.0084350780000000004,
  0.01632461,
  0.032192739999999997,
  0.065899529999999998,
  0.097892670000000001,
  0.14951810000000001,
  0.25331320000000002,
  0.39798810000000001,
  0.69384250000000003,
  1.8311549999999999,
  2.570049,
  5.0680290000000001,
  8.196809],
 [0.01047828,
  0.043950999999999997,
  0.067175460000000006,
  0.15976400000000002,
  0.27578420000000003,
  0.46731790000000001,
  0.83788469999999993,
  1.341291,
  2.2950710000000001,
  3.2220720000000003,
  5.0684379999999996,
  9.992324,
  16.32263],
 [0.067165959999999997,
  0.043947439999999997,
  0.142679,
  0.23722600000000002,
  0.38704309999999997,
  0.46704420000000002,
  1.0801190000000001,
  1.830193,
  2.59546500

In [314]:
x = free_lig

In [324]:
np.array(x).shape

(17,)

(17,)

In [325]:
type(holder)

list

In [326]:
type(holder[0])

pandas.core.series.Series

In [327]:
a = holder[0]

In [329]:
a.as_matrix()

array([ 0.04603855,  0.07301927,  0.1115632 ,  0.1925054 ,  0.2426124 ,
        0.3466809 ,  0.4411135 ,  0.5066381 ,  0.7147752 ,  0.8130621 ,
        0.8535332 ,  0.8901499 ,  0.8997859 ,  0.9460385 ,  0.9961456 ])

In [332]:
vals = a.index.values

In [333]:
b = holder[1]

In [334]:
vals

array([  7.96945700e-03,   1.49932600e-02,   3.09951900e-02,
         6.10952800e-02,   9.51486100e-02,   1.43964800e-01,
         2.43969000e-01,   3.94505100e-01,   6.86923000e-01,
         1.07939900e+00,   1.84758300e+00,   2.61864500e+00,
         4.19711500e+00,   8.12129800e+00,   1.60132400e+01])

In [336]:
np.concatenate((a,b), axis=0)

array([ 0.04603855,  0.07301927,  0.1115632 ,  0.1925054 ,  0.2426124 ,
        0.3466809 ,  0.4411135 ,  0.5066381 ,  0.7147752 ,  0.8130621 ,
        0.8535332 ,  0.8901499 ,  0.8997859 ,  0.9460385 ,  0.9961456 ,
        0.03062099,  0.05952891,  0.09614561,  0.1732334 ,  0.2310493 ,
        0.337045  ,  0.4565311 ,  0.5683084 ,  0.6588865 ,  0.8053533 ,
        0.8766595 ,  0.9171307 ,  0.9633833 ])