In [10]:

# coding: utf-8

# In[1]:

import numpy as np


# In[2]:

def dilser(low=0.001, limit=100.0, dilfactor = 2.0):
    """Returns a list containing a dilution series that ranges from
    "low" to "limit" by "dilfactor".
    """
    a = [low]
    while a[-1] <= limit:
        a.append(a[len(a)-1]*dilfactor)
    
    return np.array(a)


# In[3]:

lig = dilser()


# In[4]:

a = np.delete(lig,[15,16])


# In[5]:

b = np.delete(lig,[14,17])


# In[6]:

c = np.delete(lig,[13,15])


# In[7]:

ligset = np.array([lig,a,lig,b,c])


# In[8]:

noiseset = np.array([np.random.normal(1,0.05,ligset[i].size) for i in range(ligset.shape[0])])


# In[9]:

rtots = np.array([0.001,0.005, 0.01, 0.02, 0.05])


# In[10]:

sim_parms = dict({'k11':3.7, 'k21':1.8, 'k22':0.12, 'l20':293.0})


# In[11]:
#@profile
def wyman_sim(lig,rtot,parm):    
    k11 = parm['k11']
    k21 = parm['k21']
    k22 = parm['k22']
    l20 = parm['l20']
    
    holder = []
    
    for i in range(lig.size):
        
        ligf = ligset
        rtotf = rtots
        
        rfreetop = (np.concatenate((-1 - k11*ligf)) + \
        (np.sqrt(np.square(np.concatenate((1 + k11*ligf))) + \
        8.*l20*rtotf*np.concatenate((1 + k21*ligf + k21*k22*(np.square(ligf)))))))
        
        #rfreebottom = (4*l20*(1 + k21*ligf + k21*k22*(np.square(ligf))))
        
        #rfree = rfreetop/rfreebottom
        
        #bfrac = (k11*ligf + l20*k21*rfree*ligf + \
        #2*l20*k21*k22*rfree*(ligf**2))/(1 + 2*l20*rfree + k11*ligf + \
        #2*l20*k21*rfree*ligf + 2*l20*k21*k22*rfree*(ligf**2))
        
        holder.append(bfrac)
        
    return np.array(holder)
wyman_sim(ligset,rtots,sim_parms)

ValueError: operands could not be broadcast together with shapes (5,) (84,) 

In [6]:
ligset

array([ array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02]),
       array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         1.31072000e+02]),
       array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200

In [9]:
np.sqrt(np.concatenate(ligset))

array([  0.03162278,   0.04472136,   0.06324555,   0.08944272,
         0.12649111,   0.17888544,   0.25298221,   0.35777088,
         0.50596443,   0.71554175,   1.01192885,   1.43108351,
         2.0238577 ,   2.86216701,   4.04771541,   5.72433402,
         8.09543081,  11.44866804,   0.03162278,   0.04472136,
         0.06324555,   0.08944272,   0.12649111,   0.17888544,
         0.25298221,   0.35777088,   0.50596443,   0.71554175,
         1.01192885,   1.43108351,   2.0238577 ,   2.86216701,
         4.04771541,  11.44866804,   0.03162278,   0.04472136,
         0.06324555,   0.08944272,   0.12649111,   0.17888544,
         0.25298221,   0.35777088,   0.50596443,   0.71554175,
         1.01192885,   1.43108351,   2.0238577 ,   2.86216701,
         4.04771541,   5.72433402,   8.09543081,  11.44866804,
         0.03162278,   0.04472136,   0.06324555,   0.08944272,
         0.12649111,   0.17888544,   0.25298221,   0.35777088,
         0.50596443,   0.71554175,   1.01192885,   1.43

In [11]:
# coding: utf-8

# In[1]:

import numpy as np


# In[2]:

def dilser(low=0.001, limit=100.0, dilfactor = 2.0):
    """Returns a list containing a dilution series that ranges from
    "low" to "limit" by "dilfactor".
    """
    a = [low]
    while a[-1] <= limit:
        a.append(a[len(a)-1]*dilfactor)
    
    return np.array(a)


# In[3]:

lig = dilser()


# In[4]:

a = np.delete(lig,[15,16])


# In[5]:

b = np.delete(lig,[14,17])


# In[6]:

c = np.delete(lig,[13,15])


# In[7]:

ligset = np.array([lig,a,lig,b,c])


# In[8]:

noiseset = np.array([np.random.normal(1,0.05,ligset[i].size) for i in range(ligset.shape[0])])


# In[9]:

rtots = np.array([0.001,0.005, 0.01, 0.02, 0.05])


# In[10]:

sim_parms = dict({'k11':3.7, 'k21':1.8, 'k22':0.12, 'l20':293.0})


# In[11]:
#@profile
def wyman_sim(lig,rtot,parm):    
    k11 = parm['k11']
    k21 = parm['k21']
    k22 = parm['k22']
    l20 = parm['l20']
    
    
    ligf = ligset
    rtotf = rtots
        
    rfreetop = (np.concatenate((-1 - k11*ligf)) + \
    (np.sqrt(np.square(np.concatenate((1 + k11*ligf))) + \
    8.*l20*rtotf*np.concatenate((1 + k21*ligf + k21*k22*(np.square(ligf)))))))
    
    #rfreebottom = (4*l20*(1 + k21*ligf + k21*k22*(np.square(ligf))))
    
    #rfree = rfreetop/rfreebottom
    
    #bfrac = (k11*ligf + l20*k21*rfree*ligf + \
    #2*l20*k21*k22*rfree*(ligf**2))/(1 + 2*l20*rfree + k11*ligf + \
    #2*l20*k21*rfree*ligf + 2*l20*k21*k22*rfree*(ligf**2))
	
	return rfreetop


wyman_sim(ligset,rtots,sim_parms)

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-11-f91a510e3c6b>, line 83)

In [12]:
# coding: utf-8

# In[1]:

import numpy as np


# In[2]:

def dilser(low=0.001, limit=100.0, dilfactor = 2.0):
    """Returns a list containing a dilution series that ranges from
    "low" to "limit" by "dilfactor".
    """
    a = [low]
    while a[-1] <= limit:
        a.append(a[len(a)-1]*dilfactor)
    
    return np.array(a)


# In[3]:

lig = dilser()


# In[4]:

a = np.delete(lig,[15,16])


# In[5]:

b = np.delete(lig,[14,17])


# In[6]:

c = np.delete(lig,[13,15])


# In[7]:

ligset = np.array([lig,a,lig,b,c])


# In[8]:

noiseset = np.array([np.random.normal(1,0.05,ligset[i].size) for i in range(ligset.shape[0])])


# In[9]:

rtots = np.array([0.001,0.005, 0.01, 0.02, 0.05])


# In[10]:

sim_parms = dict({'k11':3.7, 'k21':1.8, 'k22':0.12, 'l20':293.0})


# In[11]:
#@profile
def wyman_sim(lig,rtot,parm):
    k11 = parm['k11']
    k21 = parm['k21']
    k22 = parm['k22']
    l20 = parm['l20']
    
    
    ligf = ligset
    rtotf = rtots
    
    rfreetop = (np.concatenate((-1 - k11*ligf)) + \
    (np.sqrt(np.square(np.concatenate((1 + k11*ligf))) + \
    8.*l20*rtotf*np.concatenate((1 + k21*ligf + k21*k22*(np.square(ligf)))))))
    
    return rfreetop
    
    #rfreebottom = (4*l20*(1 + k21*ligf + k21*k22*(np.square(ligf))))
    
    #rfree = rfreetop/rfreebottom
    
    #bfrac = (k11*ligf + l20*k21*rfree*ligf + \
    #2*l20*k21*k22*rfree*(ligf**2))/(1 + 2*l20*rfree + k11*ligf + \
    #2*l20*k21*rfree*ligf + 2*l20*k21*k22*rfree*(ligf**2))





wyman_sim(ligset,rtots,sim_parms)

ValueError: operands could not be broadcast together with shapes (5,) (84,) 

In [13]:

import numpy as np


# In[2]:

def dilser(low=0.001, limit=100.0, dilfactor = 2.0):
    """Returns a list containing a dilution series that ranges from
    "low" to "limit" by "dilfactor".
    """
    a = [low]
    while a[-1] <= limit:
        a.append(a[len(a)-1]*dilfactor)
    
    return np.array(a)


# In[3]:

lig = dilser()


# In[4]:

a = np.delete(lig,[15,16])


# In[5]:

b = np.delete(lig,[14,17])


# In[6]:

c = np.delete(lig,[13,15])


# In[7]:

ligset = np.array([lig,a,lig,b,c])


# In[8]:

noiseset = np.array([np.random.normal(1,0.05,ligset[i].size) for i in range(ligset.shape[0])])


# In[9]:

rtots = np.array([0.001,0.005, 0.01, 0.02, 0.05])

In [14]:
rtots

array([ 0.001,  0.005,  0.01 ,  0.02 ,  0.05 ])

In [16]:
rtots*ligset

array([ array([  1.00000000e-06,   2.00000000e-06,   4.00000000e-06,
         8.00000000e-06,   1.60000000e-05,   3.20000000e-05,
         6.40000000e-05,   1.28000000e-04,   2.56000000e-04,
         5.12000000e-04,   1.02400000e-03,   2.04800000e-03,
         4.09600000e-03,   8.19200000e-03,   1.63840000e-02,
         3.27680000e-02,   6.55360000e-02,   1.31072000e-01]),
       array([  5.00000000e-06,   1.00000000e-05,   2.00000000e-05,
         4.00000000e-05,   8.00000000e-05,   1.60000000e-04,
         3.20000000e-04,   6.40000000e-04,   1.28000000e-03,
         2.56000000e-03,   5.12000000e-03,   1.02400000e-02,
         2.04800000e-02,   4.09600000e-02,   8.19200000e-02,
         6.55360000e-01]),
       array([  1.00000000e-05,   2.00000000e-05,   4.00000000e-05,
         8.00000000e-05,   1.60000000e-04,   3.20000000e-04,
         6.40000000e-04,   1.28000000e-03,   2.56000000e-03,
         5.12000000e-03,   1.02400000e-02,   2.04800000e-02,
         4.09600000e-02,   8.19200

In [26]:
# coding: utf-8

# In[1]:

import numpy as np


# In[2]:

def dilser(low=0.001, limit=100.0, dilfactor = 2.0):
    """Returns a list containing a dilution series that ranges from
    "low" to "limit" by "dilfactor".
    """
    a = [low]
    while a[-1] <= limit:
        a.append(a[len(a)-1]*dilfactor)
    
    return np.array(a)


# In[3]:

lig = dilser()


# In[4]:

a = np.delete(lig,[15,16])


# In[5]:

b = np.delete(lig,[14,17])


# In[6]:

c = np.delete(lig,[13,15])


# In[7]:

ligset = np.array([lig,a,lig,b,c])


# In[8]:

noiseset = np.array([np.random.normal(1,0.05,ligset[i].size) for i in range(ligset.shape[0])])


# In[9]:

rtots = np.array([0.001,0.005, 0.01, 0.02, 0.05])


# In[10]:

sim_parms = dict({'k11':3.7, 'k21':1.8, 'k22':0.12, 'l20':293.0})


# In[11]:
#@profile
def wyman_sim(lig,rtot,parm):
    k11 = parm['k11']
    k21 = parm['k21']
    k22 = parm['k22']
    l20 = parm['l20']
    
    
    ligf = ligset
    ligc = np.concatenate(ligset)
    rtotf = rtots
    
    rfreetop = (np.concatenate((-1 - k11*ligf)) + \
    (np.sqrt(np.concatenate((np.square((1 + k11*ligf)) + \
    8.*l20*rtotf*(1 + k21*ligf + k21*k22*(np.square(ligf))))))))
    
    rfreebottom = np.concatenate(4*l20*(1 + k21*ligf + k21*k22*(np.square(ligf))))
    
    rfree = rfreetop/rfreebottom
    
       
    bfrac = (k11*ligc + l20*k21*rfree*ligc + \
    2*l20*k21*k22*rfree*(np.square(ligc)))/(1 + 2*l20*rfree + k11*ligc + \
    2*l20*k21*rfree*ligc + 2*l20*k21*k22*rfree*(np.square(ligc)))
    
    return bfrac





wyman_sim(ligset,rtots,sim_parms)

array([ 0.00287218,  0.0057293 ,  0.01139886,  0.02256218,  0.04420898,
        0.08495766,  0.15750031,  0.27442734,  0.43494373,  0.61140532,
        0.76276266,  0.86736558,  0.92969257,  0.9637874 ,  0.98162164,
        0.99074192,  0.99535363,  0.99767247,  0.00212201,  0.00423545,
        0.00843679,  0.01673873,  0.03295043,  0.06388646,  0.12039349,
        0.21575195,  0.3567863 ,  0.52877848,  0.69457034,  0.82154023,
        0.90281887,  0.9492021 ,  0.97402094,  0.99668726,  0.00183875,
        0.00367067,  0.00731417,  0.01452088,  0.02862117,  0.05563083,
        0.10532975,  0.19035641,  0.3191859 ,  0.4825415 ,  0.64899583,
        0.78533335,  0.87867192,  0.93494879,  0.96622051,  0.98277258,
        0.99129847,  0.99562683,  0.0016043 ,  0.00320301,  0.00638376,
        0.0126794 ,  0.02501369,  0.04870285,  0.09251507,  0.16819537,
        0.28486929,  0.43720977,  0.5996735 ,  0.741466  ,  0.84618727,
        0.91418393,  0.97630818,  0.98793257,  0.00136943,  0.00

In [20]:
ligset

array([ array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02]),
       array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         1.31072000e+02]),
       array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200

In [21]:
np.square(ligset)

array([ array([  1.00000000e-06,   4.00000000e-06,   1.60000000e-05,
         6.40000000e-05,   2.56000000e-04,   1.02400000e-03,
         4.09600000e-03,   1.63840000e-02,   6.55360000e-02,
         2.62144000e-01,   1.04857600e+00,   4.19430400e+00,
         1.67772160e+01,   6.71088640e+01,   2.68435456e+02,
         1.07374182e+03,   4.29496730e+03,   1.71798692e+04]),
       array([  1.00000000e-06,   4.00000000e-06,   1.60000000e-05,
         6.40000000e-05,   2.56000000e-04,   1.02400000e-03,
         4.09600000e-03,   1.63840000e-02,   6.55360000e-02,
         2.62144000e-01,   1.04857600e+00,   4.19430400e+00,
         1.67772160e+01,   6.71088640e+01,   2.68435456e+02,
         1.71798692e+04]),
       array([  1.00000000e-06,   4.00000000e-06,   1.60000000e-05,
         6.40000000e-05,   2.56000000e-04,   1.02400000e-03,
         4.09600000e-03,   1.63840000e-02,   6.55360000e-02,
         2.62144000e-01,   1.04857600e+00,   4.19430400e+00,
         1.67772160e+01,   6.71088

In [23]:
ligset + ligset

array([ array([  2.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         6.55360000e+01,   1.31072000e+02,   2.62144000e+02]),
       array([  2.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         2.62144000e+02]),
       array([  2.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840

In [24]:
np.concatenate(ligset) + np.concatenate(ligset)

array([  2.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         6.55360000e+01,   1.31072000e+02,   2.62144000e+02,
         2.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         2.62144000e+02,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,