In [1]:
from mods import class_test
%load_ext autoreload

In [2]:
a = class_test.WymanSim(sets=10)

In [4]:
a.ligs

array([[  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
          8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
          6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
          5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
          4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
          3.27680000e+01,   6.55360000e+01,   1.31072000e+02],
       [  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
          8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
          6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
          5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
          4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
          3.27680000e+01,   6.55360000e+01,   1.31072000e+02],
       [  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
          8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
          6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
          5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
      

In [5]:
def genfunc(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
    
        rfree = (((-1 - k11*lig)) + \
        (np.sqrt((np.square((1 + k11*lig)) + \
        8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig))))))) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        return bfrac

In [7]:
import numpy as np

In [11]:
[genfunc(a.parms,a.ligs[i],a.rtot[i]) for i in range(len(a.rtot))]

[array([ 0.00270114,  0.00538823,  0.01072068,  0.02122155,  0.04158962,
         0.07995809,  0.14838883,  0.25922436,  0.41318706,  0.58652335,
         0.74071453,  0.85171564,  0.92017061,  0.95850362,  0.97883397,
         0.98930956,  0.99462754,  0.99730691]),
 array([ 0.00245828,  0.00490498,  0.00976393,  0.01934623,  0.03798528,
         0.07328746,  0.1368788 ,  0.24163521,  0.39089596,  0.5643122 ,
         0.72336186,  0.84051004,  0.91375548,  0.95506705,  0.97705513,
         0.98840459,  0.99417112,  0.99707771]),
 array([ 0.0022312 ,  0.00445269,  0.0088668 ,  0.01758129,  0.03456848,
         0.06687522,  0.12552496,  0.22348911,  0.36624904,  0.53744654,
         0.70032845,  0.82445614,  0.90407663,  0.94972034,  0.97424055,
         0.98695999,  0.99343923,  0.99670934]),
 array([ 0.00199594,  0.0039838 ,  0.00793546,  0.01574391,  0.03099184,
         0.06009095,  0.11326691,  0.20317096,  0.33694389,  0.50263769,
         0.66730939,  0.79914398,  0.88766661,  0.

In [9]:
a.ligs.shape

(6, 18)

In [10]:
a.rtot.shape

(6,)

In [12]:
a.bfrac

array([[ 0.00270114,  0.00538823,  0.01072068,  0.02122155,  0.04158962,
         0.07995809,  0.14838883,  0.25922436,  0.41318706,  0.58652335,
         0.74071453,  0.85171564,  0.92017061,  0.95850362,  0.97883397,
         0.98930956,  0.99462754,  0.99730691],
       [ 0.00245828,  0.00490498,  0.00976393,  0.01934623,  0.03798528,
         0.07328746,  0.1368788 ,  0.24163521,  0.39089596,  0.5643122 ,
         0.72336186,  0.84051004,  0.91375548,  0.95506705,  0.97705513,
         0.98840459,  0.99417112,  0.99707771],
       [ 0.0022312 ,  0.00445269,  0.0088668 ,  0.01758129,  0.03456848,
         0.06687522,  0.12552496,  0.22348911,  0.36624904,  0.53744654,
         0.70032845,  0.82445614,  0.90407663,  0.94972034,  0.97424055,
         0.98695999,  0.99343923,  0.99670934],
       [ 0.00199594,  0.0039838 ,  0.00793546,  0.01574391,  0.03099184,
         0.06009095,  0.11326691,  0.20317096,  0.33694389,  0.50263769,
         0.66730939,  0.79914398,  0.88766661,  0.940

In [13]:
    def fitfunc(parm,lig,data,rtot,eps=None):
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
    
        ligc = np.concatenate(lig)
        datac = np.concatenate(data)
        rtot_tr = rtot[:,None]
    
        rfree = (((-1 - k11*ligc)) + \
        (np.sqrt(np.concatenate((np.square((1 + k11*lig)) + \
        8.*l20*rtot_tr*(1 + k21*lig + k21*k22*(np.square(lig)))))))) \
        / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc))))    
       
        bfrac = (k11*ligc + l20*k21*rfree*ligc + \
        2*l20*k21*k22*rfree*(np.square(ligc))) \
        / (1 + 2*l20*rfree + k11*ligc + \
        2*l20*k21*rfree*ligc + 2*l20*k21*k22*rfree*(np.square(ligc)))
    
        residual = (bfrac - datac)

        if eps is None:
            return residual
        else:
            weights = 1/(np.concatenate(eps))
            return (residual*weights)

In [14]:
fitfunc(a.parms,a.ligs,a.bfrac,a.rtot)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [18]:
np.concatenate(genfunc(a.parms,a.ligs,a.rtot[:,None]) - a.bfrac)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [21]:
b = a.rtot[:,None]

In [22]:
b.shape

(6, 1)

In [23]:
import matplotlib.pyplot as plt
from scipy import optimize
from mods import prep, plotter, models
%matplotlib inline
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
WT_08_lbl, WT_08_rtot, WT_08_lig, WT_08_sat = prep.datprep('data/EGFR_WT_08_Sat.csv','data/EGFR_WT_08_Rtot.csv')
WT_09_lbl, WT_09_rtot, WT_09_lig, WT_09_sat = prep.datprep('data/EGFR_WT_09_Sat.csv','data/EGFR_WT_09_Rtot.csv')
WT_11_lbl, WT_11_rtot, WT_11_lig, WT_11_sat = prep.datprep('data/EGFR_WT_11_Sat.csv','data/EGFR_WT_11_Rtot.csv')

hootie hoo! the indices match!
hootie hoo! the indices match!
hootie hoo! the indices match!


In [92]:
[genfunc(np.array([5.,2.,0.5,100]),WT_09_lig[i],WT_09_rtot[i]) for i in range(len(WT_09_rtot))]

[array([ 0.07356727,  0.13805996,  0.26391362,  0.4066037 ,  0.54476812,
         0.6653328 ,  0.77815172,  0.83727598,  0.89864326,  0.92572586,
         0.95274448,  0.96779755,  0.97619503,  0.98374601]),
 array([ 0.03897864,  0.07224109,  0.13627453,  0.24531341,  0.32900344,
         0.39573137,  0.51625286,  0.63526762,  0.76111632,  0.82358509,
         0.89037168,  0.92215386,  0.94964638,  0.97470659,  0.98292272]),
 array([ 0.03336024,  0.06828017,  0.07497334,  0.21708435,  0.29316284,
         0.35939415,  0.47365107,  0.59939562,  0.73877076,  0.80042994,
         0.87817461,  0.91190698,  0.94420723,  0.97177728,  0.98133606]),
 array([ 0.05004885,  0.0765528 ,  0.15058116,  0.2548084 ,  0.38488904,
         0.52541559,  0.67514943,  0.76496196,  0.85361188,  0.89664831,
         0.93572981,  0.95764163,  0.96780104,  0.97869971]),
 array([ 0.0257937 ,  0.05413871,  0.1046447 ,  0.1542589 ,  0.215073  ,
         0.32066339,  0.43963102,  0.59265494,  0.69575725,  0.804518

In [30]:
genfunc(a.parms,a.ligs,a.rtot[:,None])

array([[ 0.00270114,  0.00538823,  0.01072068,  0.02122155,  0.04158962,
         0.07995809,  0.14838883,  0.25922436,  0.41318706,  0.58652335,
         0.74071453,  0.85171564,  0.92017061,  0.95850362,  0.97883397,
         0.98930956,  0.99462754,  0.99730691],
       [ 0.00245828,  0.00490498,  0.00976393,  0.01934623,  0.03798528,
         0.07328746,  0.1368788 ,  0.24163521,  0.39089596,  0.5643122 ,
         0.72336186,  0.84051004,  0.91375548,  0.95506705,  0.97705513,
         0.98840459,  0.99417112,  0.99707771],
       [ 0.0022312 ,  0.00445269,  0.0088668 ,  0.01758129,  0.03456848,
         0.06687522,  0.12552496,  0.22348911,  0.36624904,  0.53744654,
         0.70032845,  0.82445614,  0.90407663,  0.94972034,  0.97424055,
         0.98695999,  0.99343923,  0.99670934],
       [ 0.00199594,  0.0039838 ,  0.00793546,  0.01574391,  0.03099184,
         0.06009095,  0.11326691,  0.20317096,  0.33694389,  0.50263769,
         0.66730939,  0.79914398,  0.88766661,  0.940

In [33]:
genfunc(a.parms,WT_09_lig,WT_09_rtot[:,None])

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [34]:
type(WT_09_lig)

numpy.ndarray

In [37]:
np.sqrt(np.concatenate(WT_09_lig))

array([ 0.13091024,  0.18559224,  0.2766845 ,  0.38090537,  0.50126739,
        0.64364027,  0.85180086,  1.02963731,  1.34876388,  1.59766267,
        2.03009458,  2.47726846,  2.89288697,  3.51352387,  0.1015169 ,
        0.14037407,  0.19901827,  0.2836207 ,  0.34631214,  0.3982847 ,
        0.5036741 ,  0.63696868,  0.85137254,  1.02400342,  1.34086241,
        1.6134835 ,  2.02925922,  2.89189523,  3.53067557,  0.10201946,
        0.14827464,  0.15585368,  0.28498567,  0.34622507,  0.40019233,
        0.5009982 ,  0.6367684 ,  0.85925293,  1.01366119,  1.34106152,
        1.59695053,  2.02881862,  2.87712322,  3.54791065,  0.13553479,
        0.16966352,  0.24663055,  0.33943379,  0.4533996 ,  0.59365512,
        0.79717539,  0.98333656,  1.29457831,  1.56465971,  2.00848923,
        2.48904861,  2.86229576,  3.52853794,  0.11384068,  0.16711119,
        0.23808736,  0.29652396,  0.36201796,  0.47167022,  0.60245348,
        0.80899011,  1.00291924,  1.32668308,  1.58786712,  2.01

In [51]:
def genfunc2(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
        
        ligc = np.concatenate(lig)
    
        rfree = (((-1 - k11*ligc)) + \
        (np.sqrt(np.concatenate((np.square((1 + k11*lig)) + \
        8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig))))))) \
        / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc)))))    
       
        bfrac = (k11*ligc + l20*k21*rfree*ligc + \
        2*l20*k21*k22*rfree*(np.square(ligc))) \
        / (1 + 2*l20*rfree + k11*ligc + \
        2*l20*k21*rfree*ligc + 2*l20*k21*k22*rfree*(np.square(ligc)))
    
        return bfrac

In [49]:
genfunc2(np.array([5.,2.,0.5,100]),WT_09_lig[1],WT_09_rtot[1]) 

ValueError: zero-dimensional arrays cannot be concatenated

In [52]:
genfunc2(a.parms,WT_09_lig,WT_09_rtot[:,None])

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [64]:
def wrap1(parm,lig,rtot):
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
        
    ligc = np.concatenate(lig)
    
    return ((-1 - k11*ligc) + ((np.sqrt(np.concatenate((np.square((1 + k11*lig)) \
           + 8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig))))))) \
           / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc))))))

In [65]:
wrap1(a.parms,WT_09_lig,WT_09_rtot)

array([ -1.04836208,  -1.10026579,  -1.22655746,  -1.43211086,
        -1.75059496,  -2.23955648,  -3.17340736,  -4.17719685,
        -6.45435626,  -8.6545891 , -13.36116504, -19.40821452,
       -26.10430662, -38.03284172,  -1.0265766 ,  -1.0547874 ,
        -1.11452409,  -1.2370706 ,  -1.35558699,  -1.47172005,
        -1.75696964,  -2.21319623,  -3.17068079,  -4.14206151,
        -6.39031206,  -8.80679875, -13.35085107, -26.08702212,
       -38.39526121,  -1.02506992,  -1.0598481 ,  -1.06677205,
        -1.23775441,  -1.35384001,  -1.47480011,  -1.74755709,
        -2.21127732,  -3.21024611,  -4.0780989 ,  -6.3914102 ,
        -8.64716381, -13.34522649, -25.83121251, -38.7611769 ,
        -1.04690046,  -1.07821491,  -1.17453   ,  -1.33798717,
        -1.60946165,  -2.05054489,  -2.90043268,  -3.89537528,
        -6.02308118,  -8.34029124, -13.09859555, -19.58319079,
       -25.57568961, -38.34975287,  -1.02229928,  -1.06742535,
        -1.15411457,  -1.24825042,  -1.37816345,  -1.65

In [73]:
def rfr3(parm,lig,rtot):
    
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
        
    ligc = np.concatenate(lig)
    
    return (((-1 - k11*ligc)) + \
        (np.sqrt((np.square((1 + k11*lig)) + \
        8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig)))))) \
        / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc)))))    

In [75]:
rfr3(np.array([5.,2.,0.2,100.]),WT_09_lig[1],WT_09_rtot[1])

ValueError: zero-dimensional arrays cannot be concatenated

In [78]:
def wyman_sp_rfree(parm,lig,rtot):
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
    
    ligc = np.concatenate(lig)
    
    return (((-1 - k11*ligc)) + \
    (np.sqrt(np.concatenate((np.square((1 + k11*lig)) + \
    8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig)))))))) \
    / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc))))    

In [79]:
wyman_sp_rfree(a.parms,WT_09_lig, WT_09_rtot)

array([  5.09107613e-04,   4.87658586e-04,   4.42200870e-04,
         3.83745739e-04,   3.18280209e-04,   2.52020499e-04,
         1.80157542e-04,   1.37829525e-04,   8.98705502e-05,
         6.72474182e-05,   4.37053102e-05,   3.01443286e-05,
         2.24352888e-05,   1.54131246e-05,   1.81525220e-03,
         1.78004088e-03,   1.70971928e-03,   1.58124491e-03,
         1.47383062e-03,   1.38164693e-03,   1.19714592e-03,
         9.85739609e-04,   7.18332166e-04,   5.62930828e-04,
         3.74848008e-04,   2.75713113e-04,   1.84099543e-04,
         9.53034932e-05,   6.50005257e-05,   3.62855251e-03,
         3.55560218e-03,   3.54143137e-03,   3.22444464e-03,
         3.04000505e-03,   2.86919231e-03,   2.54700354e-03,
         2.13948777e-03,   1.59223772e-03,   1.30324196e-03,
         8.78779944e-04,   6.67131766e-04,   4.44368829e-04,
         2.35481506e-04,   1.58389748e-04,   5.66444764e-03,
         5.57457408e-03,   5.31605678e-03,   4.93051932e-03,
         4.40480765e-03,

def wyman_sp_rfree(parm,lig,rtot):
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
    
    ligc = np.concatenate(lig)
    
    return (((-1 - k11*ligc)) + \
    (np.sqrt(np.concatenate((np.square((1 + k11*lig)) + \
    8.*l20*rtot*(1 + k21*lig + k21*k22*(np.square(lig)))))))) \
    / (4*l20*(1 + k21*ligc + k21*k22*(np.square(ligc)))) 

In [89]:
def wyman_sp_rfreeMOD(parm,lig,rtot):
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
    
    rtotTR = rtot[:,None]
    #ligc = np.concatenate(lig)
    
    return (((-1 - k11*lig)) + \
    (np.sqrt(np.concatenate(np.concatenate((np.square((1 + k11*lig)) + \
    8.*l20*rtotTR*(1 + k21*lig + k21*k22*(np.square(lig))))))))) \
    / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig)))) 

In [90]:
wyman_sp_rfreeMOD(a.parms,WT_09_lig, WT_09_rtot)

ValueError: operands could not be broadcast together with shapes (5,) (360,) 

In [91]:
8+5+32+19+23+9+50+5+15+72+22+21+18+30+20+30


379

In [93]:
genfunc(np.array([5.,2.,0.5,100]),WT_09_lig,WT_09_rtot)

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [94]:
genfunc(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

ValueError: operands could not be broadcast together with shapes (6,) (6,18) 

In [97]:
def genfunc2(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
        
        rtotTR = rtot[:,None]
    
        rfree = (((-1 - k11*lig)) + \
        (np.sqrt((np.square((1 + k11*lig)) + \
        8.*l20*rtotTR*(1 + k21*lig + k21*k22*(np.square(lig))))))) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        return bfrac

In [98]:
genfunc2(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

array([[ 0.00439846,  0.00876128,  0.01738165,  0.03421209,  0.06631457,
         0.12488398,  0.22341996,  0.36808302,  0.54199297,  0.70628381,
         0.829668  ,  0.90761511,  0.95179705,  0.97536764,  0.98754741,
         0.99373913,  0.99686086,  0.99842825],
       [ 0.00391463,  0.00780227,  0.01549759,  0.03057525,  0.05953097,
         0.11303046,  0.20501916,  0.34459292,  0.51919852,  0.6898572 ,
         0.82026074,  0.90283286,  0.94945441,  0.97422155,  0.98698269,
         0.99345914,  0.99672149,  0.99835873],
       [ 0.0034618 ,  0.00690302,  0.01372442,  0.0271274 ,  0.05300848,
         0.10132739,  0.18598294,  0.31843766,  0.4912778 ,  0.66774559,
         0.80668263,  0.89563944,  0.94585343,  0.97244055,  0.98610038,
         0.99302049,  0.99650286,  0.99824959],
       [ 0.00299235,  0.00596947,  0.01187844,  0.02351808,  0.04610622,
         0.08868337,  0.16461872,  0.28714086,  0.45463205,  0.63551939,
         0.78505902,  0.88349768,  0.93957415,  0.969

In [99]:
genfunc2(np.array([5.,2.,0.5,100]),WT_09_lig,WT_09_rtot)

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [102]:
np.dtype(WT_09_lig)

TypeError: data type not understood

In [106]:
b = WT_09_lig.astype('f8')

ValueError: setting an array element with a sequence.

In [116]:
b = np.array([np.array([1,2]), np.array([2, 3, 4])])

In [111]:
np.sqrt([[1,2], [2, 3, 4]])

AttributeError: 'list' object has no attribute 'sqrt'

In [112]:
import math

In [113]:
math.sqrt(b)

TypeError: only length-1 arrays can be converted to Python scalars

In [115]:
b

array([[1, 2], [2, 3, 4]], dtype=object)

In [117]:
b

array([array([1, 2]), array([2, 3, 4])], dtype=object)

In [121]:
b**(0.5)

array([array([ 1.        ,  1.41421356]),
       array([ 1.41421356,  1.73205081,  2.        ])], dtype=object)

In [122]:
np.sqrt(b)

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [123]:
def genfunc3(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
        
        rtotTR = rtot[:,None]
    
        rfree = (((-1 - k11*lig)) + \
        ((np.square((1 + k11*lig)) + \
        8.*l20*rtotTR*(1 + k21*lig + k21*k22*(np.square(lig)))))**0.5) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        return bfrac

In [124]:
genfunc2(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

array([[ 0.00439846,  0.00876128,  0.01738165,  0.03421209,  0.06631457,
         0.12488398,  0.22341996,  0.36808302,  0.54199297,  0.70628381,
         0.829668  ,  0.90761511,  0.95179705,  0.97536764,  0.98754741,
         0.99373913,  0.99686086,  0.99842825],
       [ 0.00391463,  0.00780227,  0.01549759,  0.03057525,  0.05953097,
         0.11303046,  0.20501916,  0.34459292,  0.51919852,  0.6898572 ,
         0.82026074,  0.90283286,  0.94945441,  0.97422155,  0.98698269,
         0.99345914,  0.99672149,  0.99835873],
       [ 0.0034618 ,  0.00690302,  0.01372442,  0.0271274 ,  0.05300848,
         0.10132739,  0.18598294,  0.31843766,  0.4912778 ,  0.66774559,
         0.80668263,  0.89563944,  0.94585343,  0.97244055,  0.98610038,
         0.99302049,  0.99650286,  0.99824959],
       [ 0.00299235,  0.00596947,  0.01187844,  0.02351808,  0.04610622,
         0.08868337,  0.16461872,  0.28714086,  0.45463205,  0.63551939,
         0.78505902,  0.88349768,  0.93957415,  0.969

In [125]:
genfunc3(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

array([[ 0.00439846,  0.00876128,  0.01738165,  0.03421209,  0.06631457,
         0.12488398,  0.22341996,  0.36808302,  0.54199297,  0.70628381,
         0.829668  ,  0.90761511,  0.95179705,  0.97536764,  0.98754741,
         0.99373913,  0.99686086,  0.99842825],
       [ 0.00391463,  0.00780227,  0.01549759,  0.03057525,  0.05953097,
         0.11303046,  0.20501916,  0.34459292,  0.51919852,  0.6898572 ,
         0.82026074,  0.90283286,  0.94945441,  0.97422155,  0.98698269,
         0.99345914,  0.99672149,  0.99835873],
       [ 0.0034618 ,  0.00690302,  0.01372442,  0.0271274 ,  0.05300848,
         0.10132739,  0.18598294,  0.31843766,  0.4912778 ,  0.66774559,
         0.80668263,  0.89563944,  0.94585343,  0.97244055,  0.98610038,
         0.99302049,  0.99650286,  0.99824959],
       [ 0.00299235,  0.00596947,  0.01187844,  0.02351808,  0.04610622,
         0.08868337,  0.16461872,  0.28714086,  0.45463205,  0.63551939,
         0.78505902,  0.88349768,  0.93957415,  0.969

In [127]:
%timeit genfunc2(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

10000 loops, best of 3: 80.8 µs per loop


In [128]:
%timeit genfunc3(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

10000 loops, best of 3: 82.6 µs per loop


In [129]:
genfunc3(np.array([5.,2.,0.5,100]),WT_09_lig,WT_09_rtot)

array([[ array([ 0.07356727,  0.13805996,  0.26391362,  0.4066037 ,  0.54476812,
        0.6653328 ,  0.77815172,  0.83727598,  0.89864326,  0.92572586,
        0.95274448,  0.96779755,  0.97619503,  0.98374601]),
        array([ 0.04550991,  0.08370906,  0.15566727,  0.27375792,  0.36097137,
        0.42862248,  0.5471798 ,  0.66060898,  0.777976  ,  0.83576134,
        0.89756107,  0.92707592,  0.95270729,  0.97617906,  0.98390118]),
        array([ 0.0459419 ,  0.09254156,  0.10130536,  0.2756934 ,  0.36085377,
        0.43099946,  0.54449752,  0.6604659 ,  0.78117888,  0.83292897,
        0.89758855,  0.92566424,  0.95268766,  0.97593933,  0.9840549 ]),
        array([ 0.07846127,  0.1179399 ,  0.22129512,  0.35164346,  0.49392378,
        0.62786754,  0.75413452,  0.82421914,  0.89087396,  0.92278947,
        0.95176852,  0.96809258,  0.97569507,  0.98388197]),
        array([ 0.05659936,  0.11480487,  0.209271  ,  0.29201786,  0.38196813,
        0.51398008,  0.63481844,  0.75961

In [135]:
def genfunc4(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
        
        #rtotTR = rtot[:,None]
        rtotTR = rtot
    
        rfree = (((-1 - k11*lig)) + \
        ((np.square((1 + k11*lig)) + \
        8.*l20*rtotTR*(1 + k21*lig + k21*k22*(np.square(lig)))))**0.5) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        return np.concatenate(bfrac)

In [136]:
genfunc4(np.array([5.,2.,0.5,100]),WT_09_lig,WT_09_rtot)

array([ 0.07356727,  0.13805996,  0.26391362,  0.4066037 ,  0.54476812,
        0.6653328 ,  0.77815172,  0.83727598,  0.89864326,  0.92572586,
        0.95274448,  0.96779755,  0.97619503,  0.98374601,  0.03897864,
        0.07224109,  0.13627453,  0.24531341,  0.32900344,  0.39573137,
        0.51625286,  0.63526762,  0.76111632,  0.82358509,  0.89037168,
        0.92215386,  0.94964638,  0.97470659,  0.98292272,  0.03336024,
        0.06828017,  0.07497334,  0.21708435,  0.29316284,  0.35939415,
        0.47365107,  0.59939562,  0.73877076,  0.80042994,  0.87817461,
        0.91190698,  0.94420723,  0.97177728,  0.98133606,  0.05004885,
        0.0765528 ,  0.15058116,  0.2548084 ,  0.38488904,  0.52541559,
        0.67514943,  0.76496196,  0.85361188,  0.89664831,  0.93572981,
        0.95764163,  0.96780104,  0.97869971,  0.0257937 ,  0.05413871,
        0.1046447 ,  0.1542589 ,  0.215073  ,  0.32066339,  0.43963102,
        0.59265494,  0.69575725,  0.80451843,  0.85691144,  0.90

In [141]:
WT_09_lig.shape == WT_09_rtot.shape

True

In [144]:
WT_09_rtot.shape[0]

5

In [142]:
a.ligs.ndim

2

In [143]:
a.rtot.ndim

1

In [171]:
def genfunc5(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]
        
        assert lig.shape[0] == rtot.shape[0], 'First dimensions of ligs and rtots must match' 
        
        if rtot.ndim != lig.ndim:
            rtotX = rtot[:,None]
        else:
            rtotX = rtot
        
        rfree = (((-1 - k11*lig)) + \
        ((np.square((1 + k11*lig)) + \
        8.*l20*rtotX*(1 + k21*lig + k21*k22*(np.square(lig)))))**0.5) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        return np.concatenate(bfrac)
    

In [172]:
%timeit genfunc5(np.array([5.,2.,0.5,100]),WT_09_lig,WT_09_rtot)

1000 loops, best of 3: 451 µs per loop


In [173]:
%timeit genfunc5(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

10000 loops, best of 3: 89.3 µs per loop


In [174]:
[genfunc5(a.parms,a.ligs[i],a.rtot[i]) for i in range(len(a.rtot))]

IndexError: tuple index out of range

In [235]:
def genfunc6(parm,lig,rtot):
        '''Generates ligand binding data according to Wyman model.
        Takes numpy arrays containing parameters k11,k21,k22,l20; 
        free ligand concentrations, and total receptor concentrations.
        Must be iterated against ligand data, i.e., for loop required when
        used for more than one receptor concentration. In fitting functions,
        the datasets are concentatenated for faster operation'''
    
        k11 = parm[0]
        k21 = parm[1]
        k22 = parm[2]
        l20 = parm[3]

        if ((rtot.ndim > 0) and (rtot.ndim != lig.ndim)):
            rtotX = rtot[:,None] #adds dimension so that it can be broadcast
        else:
            rtotX = rtot #dimensions of lig and rtot

        rfree = (((-1 - k11*lig)) + \
        ((np.square((1 + k11*lig)) + \
        8.*l20*rtotX*(1 + k21*lig + k21*k22*(np.square(lig)))))**0.5) \
        / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
       
        bfrac = (k11*lig + l20*k21*rfree*lig + \
        2*l20*k21*k22*rfree*(np.square(lig))) \
        / (1 + 2*l20*rfree + k11*lig + \
        2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
        if ((rtot.ndim > 0) and (rtot.ndim != lig.ndim)):
            return bfrac.flatten()
        elif (rtot.ndim == 0):
            return bfrac.flatten()
        else:
            return np.concatenate(bfrac)

In [239]:
%timeit [genfunc6(a.parms,a.ligs[i],a.rtot[i]) for i in range(len(a.rtot))]

1000 loops, best of 3: 438 µs per loop


In [240]:
%timeit genfunc6(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

10000 loops, best of 3: 85.8 µs per loop


In [246]:
genfunc6(a.parms,WT_09_lig,WT_09_rtot)

array([ 0.04596009,  0.08836981,  0.17761402,  0.29110022,  0.41648583,
        0.54154217,  0.67505725,  0.75266283,  0.83965959,  0.88035239,
        0.92246256,  0.94661003,  0.96030153,  0.97275059,  0.02473583,
        0.04629043,  0.08903169,  0.1660622 ,  0.22941482,  0.28301881,
        0.38817119,  0.5051399 ,  0.64766685,  0.72768617,  0.82174705,
        0.87008786,  0.91399712,  0.95585221,  0.96997673,  0.0218914 ,
        0.0451551 ,  0.04965672,  0.14887461,  0.2053043 ,  0.25671368,
        0.35146085,  0.46715811,  0.61529696,  0.69020804,  0.79611162,
        0.84709952,  0.89946846,  0.94737549,  0.96476433,  0.0340837 ,
        0.05236282,  0.10435895,  0.18030873,  0.28084039,  0.39932351,
        0.54256988,  0.64139733,  0.75379003,  0.81603523,  0.87866033,
        0.91701743,  0.93575522,  0.95661776,  0.01922392,  0.04034699,
        0.07801274,  0.11510496,  0.1608009 ,  0.24119159,  0.33452393,
        0.46249802,  0.55774398,  0.67305879,  0.73805821,  0.81

In [243]:
[genfunc6(a.parms,WT_09_lig[i],WT_09_rtot[i]) for i in range(len(WT_09_rtot))]

[array([ 0.04596009,  0.08836981,  0.17761402,  0.29110022,  0.41648583,
         0.54154217,  0.67505725,  0.75266283,  0.83965959,  0.88035239,
         0.92246256,  0.94661003,  0.96030153,  0.97275059]),
 array([ 0.02473583,  0.04629043,  0.08903169,  0.1660622 ,  0.22941482,
         0.28301881,  0.38817119,  0.5051399 ,  0.64766685,  0.72768617,
         0.82174705,  0.87008786,  0.91399712,  0.95585221,  0.96997673]),
 array([ 0.0218914 ,  0.0451551 ,  0.04965672,  0.14887461,  0.2053043 ,
         0.25671368,  0.35146085,  0.46715811,  0.61529696,  0.69020804,
         0.79611162,  0.84709952,  0.89946846,  0.94737549,  0.96476433]),
 array([ 0.0340837 ,  0.05236282,  0.10435895,  0.18030873,  0.28084039,
         0.39932351,  0.54256988,  0.64139733,  0.75379003,  0.81603523,
         0.87866033,  0.91701743,  0.93575522,  0.95661776]),
 array([ 0.01922392,  0.04034699,  0.07801274,  0.11510496,  0.1608009 ,
         0.24119159,  0.33452393,  0.46249802,  0.55774398,  0.673058

In [211]:
WT_09_lig.ndim

1

In [212]:
WT_09_rtot.ndim

1

In [214]:
a.ligs.ndim

2

In [215]:
a.rtot.ndim

1

In [247]:
def wymfunc(parm,lig,rtot):
    '''
    Model function for dimerizing, single-site receptors as derived in (Wyman and Gill, Binding and Linkage, 1990) and used by (Macdonald and Pike, ...EGF-binding...negative cooperativity...aggregating system, 2008).
    
   Takes numpy array of parameters [k11,k21,k22,l20], numpy array of free ligand concentrations, and total receptor concentration. Returns the fraction of receptor bound to ligand.
    
    To generate a data set, iterate over an array of desired receptor concentrations, e.g.: [wymfunc(parm,lig,i) for i in array_of_rtots]
    
    For use in curve fitting, the output is flattened when a full dataset is provided. For example, an objective function for use with scipy.optimize.least_squares is readily constructed as: (wymfun(parm_guess,lig,rtot) - actual_data)
    '''
    
    #check if multiple receptor concentrations are being used
    #if so, ens
    if ((rtot.ndim > 0) and (rtot.ndim != lig.ndim)):
        rtotX = rtot[:,None] #adds dimension so that it can be broadcast
    else:
        rtotX = rtot #dimensions of lig and rtot
    
    #unpack parameters
    k11 = parm[0]
    k21 = parm[1]
    k22 = parm[2]
    l20 = parm[3]
    
    ### START MODEL FUNCTION ###
    
    #calculate concentration of free (unoccupied) receptor
    rfree = (((-1 - k11*lig)) + \
    ((np.square((1 + k11*lig)) + \
    8.*l20*rtotX*(1 + k21*lig + k21*k22*(np.square(lig)))))**0.5) \
    / (4*l20*(1 + k21*lig + k21*k22*(np.square(lig))))    
   
    #calculate bound fraction
    bfrac = (k11*lig + l20*k21*rfree*lig + \
    2*l20*k21*k22*rfree*(np.square(lig))) \
    / (1 + 2*l20*rfree + k11*lig + \
    2*l20*k21*rfree*lig + 2*l20*k21*k22*rfree*(np.square(lig)))
    
    ### END MODEL FUNCTION ###
    
    #flatten output depending on input
    if ((rtot.ndim > 0) and (rtot.ndim != lig.ndim)):
        return bfrac.flatten()
    elif (rtot.ndim == 0):
        return bfrac.flatten()
    else:
        return np.concatenate(bfrac)

In [249]:
wymfunc(a.parms,WT_09_lig[1],WT_09_rtot[1])

array([ 0.02473583,  0.04629043,  0.08903169,  0.1660622 ,  0.22941482,
        0.28301881,  0.38817119,  0.5051399 ,  0.64766685,  0.72768617,
        0.82174705,  0.87008786,  0.91399712,  0.95585221,  0.96997673])

In [250]:
wymfunc(np.array([5.,2.,0.5,100]),a.ligs,a.rtot)

array([ 0.00439846,  0.00876128,  0.01738165,  0.03421209,  0.06631457,
        0.12488398,  0.22341996,  0.36808302,  0.54199297,  0.70628381,
        0.829668  ,  0.90761511,  0.95179705,  0.97536764,  0.98754741,
        0.99373913,  0.99686086,  0.99842825,  0.00391463,  0.00780227,
        0.01549759,  0.03057525,  0.05953097,  0.11303046,  0.20501916,
        0.34459292,  0.51919852,  0.6898572 ,  0.82026074,  0.90283286,
        0.94945441,  0.97422155,  0.98698269,  0.99345914,  0.99672149,
        0.99835873,  0.0034618 ,  0.00690302,  0.01372442,  0.0271274 ,
        0.05300848,  0.10132739,  0.18598294,  0.31843766,  0.4912778 ,
        0.66774559,  0.80668263,  0.89563944,  0.94585343,  0.97244055,
        0.98610038,  0.99302049,  0.99650286,  0.99824959,  0.00299235,
        0.00596947,  0.01187844,  0.02351808,  0.04610622,  0.08868337,
        0.16461872,  0.28714086,  0.45463205,  0.63551939,  0.78505902,
        0.88349768,  0.93957415,  0.9692818 ,  0.98452202,  0.99

In [251]:
wymfunc(a.parms,WT_09_lig,WT_09_rtot)

array([ 0.04596009,  0.08836981,  0.17761402,  0.29110022,  0.41648583,
        0.54154217,  0.67505725,  0.75266283,  0.83965959,  0.88035239,
        0.92246256,  0.94661003,  0.96030153,  0.97275059,  0.02473583,
        0.04629043,  0.08903169,  0.1660622 ,  0.22941482,  0.28301881,
        0.38817119,  0.5051399 ,  0.64766685,  0.72768617,  0.82174705,
        0.87008786,  0.91399712,  0.95585221,  0.96997673,  0.0218914 ,
        0.0451551 ,  0.04965672,  0.14887461,  0.2053043 ,  0.25671368,
        0.35146085,  0.46715811,  0.61529696,  0.69020804,  0.79611162,
        0.84709952,  0.89946846,  0.94737549,  0.96476433,  0.0340837 ,
        0.05236282,  0.10435895,  0.18030873,  0.28084039,  0.39932351,
        0.54256988,  0.64139733,  0.75379003,  0.81603523,  0.87866033,
        0.91701743,  0.93575522,  0.95661776,  0.01922392,  0.04034699,
        0.07801274,  0.11510496,  0.1608009 ,  0.24119159,  0.33452393,
        0.46249802,  0.55774398,  0.67305879,  0.73805821,  0.81

In [252]:
import sys

In [253]:
sys.path

['',
 '/Users/michael/miniconda3/envs/fitter/lib/python35.zip',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/plat-darwin',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/lib-dynload',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/corner-2.0.1-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/emcee-2.2.1-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/IPython/extensions',
 '/Users/michael/.ipython']

In [254]:
sys.path.append('/Users/michael/ligbind/')

In [264]:
import ligbind

In [265]:
ligbind.test(a.parms,WT_09_lig,WT_09_rtot)

array([ 0.04596009,  0.08836981,  0.17761402,  0.29110022,  0.41648583,
        0.54154217,  0.67505725,  0.75266283,  0.83965959,  0.88035239,
        0.92246256,  0.94661003,  0.96030153,  0.97275059,  0.02473583,
        0.04629043,  0.08903169,  0.1660622 ,  0.22941482,  0.28301881,
        0.38817119,  0.5051399 ,  0.64766685,  0.72768617,  0.82174705,
        0.87008786,  0.91399712,  0.95585221,  0.96997673,  0.0218914 ,
        0.0451551 ,  0.04965672,  0.14887461,  0.2053043 ,  0.25671368,
        0.35146085,  0.46715811,  0.61529696,  0.69020804,  0.79611162,
        0.84709952,  0.89946846,  0.94737549,  0.96476433,  0.0340837 ,
        0.05236282,  0.10435895,  0.18030873,  0.28084039,  0.39932351,
        0.54256988,  0.64139733,  0.75379003,  0.81603523,  0.87866033,
        0.91701743,  0.93575522,  0.95661776,  0.01922392,  0.04034699,
        0.07801274,  0.11510496,  0.1608009 ,  0.24119159,  0.33452393,
        0.46249802,  0.55774398,  0.67305879,  0.73805821,  0.81

In [266]:
%autoreload

In [267]:
ligbind.test_helper()

AttributeError: module 'ligbind' has no attribute 'test_helper'

In [268]:
ligbind.helpers.dilser()

array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02])