In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mods import models, ligtools, plotter, prep
from scipy import optimize
import corner
%matplotlib inline
%load_ext autoreload

In [2]:
WT_08_lbl, WT_08_rtot, WT_08_lig, WT_08_sat = prep.datprep('data/EGFR_WT_08_Sat.csv','data/EGFR_WT_08_Rtot.csv')

hootie hoo! the indices match!


In [3]:
WT_08_rtot

array([ 0.001439,  0.002422,  0.003392,  0.002718,  0.01216 ,  0.02594 ])

In [13]:
bound1 = ((0.0,0.0,0.0,0.0),(100.0,100.0,100.0,10000.0))

In [5]:
WT_09_lbl, WT_09_rtot, WT_09_lig, WT_09_sat = prep.datprep('data/EGFR_WT_09_Sat.csv','data/EGFR_WT_09_Rtot.csv')

hootie hoo! the indices match!


In [7]:
guess = np.array([5.,3.,0.6,100.])

In [14]:
res_wt09 = optimize.least_squares(models.wyman_sp,guess,bounds=bound1,args=(WT_09_lig,WT_09_sat,WT_09_rtot))

In [15]:
res_wt09.x

array([  4.49638827e+00,   1.92956941e+00,   2.02802412e-01,
         1.08208681e+03])

In [25]:
type(WT_09_lig)

numpy.ndarray

In [24]:
type(WT_09_sat)

numpy.ndarray

In [22]:
type(WT_09_rtot)

numpy.ndarray

In [27]:
WT_09_sat*np.array([10,100,1000,10000,100000])

array([ array([  0.4267487,   0.7219977,   1.823194 ,   3.0881   ,   3.939354 ,
         5.38879  ,   7.396108 ,   7.791709 ,   9.324073 ,   9.14133  ,
         9.702964 ,   9.190478 ,  10.26665  ,  10.2495   ]),
       array([   2.364097,    4.692846,    8.471032,   15.34647 ,   21.57494 ,
         26.55414 ,   35.88522 ,   45.73236 ,   64.87842 ,   68.83354 ,
         77.13876 ,   89.35084 ,   89.59837 ,   96.47381 ,  100.4316  ]),
       array([  15.39294,   34.64131,   36.79492,  120.4458 ,  170.3361 ,
        228.394  ,  296.916  ,  400.557  ,  512.5622 ,  655.2897 ,
        798.2227 ,  833.6276 ,  856.7631 ,  939.9583 ,  983.6827 ]),
       array([  117.7382,   679.1044,  1181.224 ,  1930.07  ,  2699.022 ,
        3405.689 ,  4711.433 ,  5706.022 ,  7279.76  ,  7448.295 ,
        8381.671 ,  8757.077 ,  9069.215 ,  8949.114 ]),
       array([  1352.529,   3072.73 ,   5200.417,   8748.945,  12500.32 ,
        20391.8  ,  29724.67 ,  42782.11 ,  53141.74 ,  65164.38 ,
        70357

In [30]:
WT_09_sat.shape

(5,)

In [34]:
WT_09_sat

array([ array([ 0.04267487,  0.07219977,  0.1823194 ,  0.30881   ,  0.3939354 ,
        0.538879  ,  0.7396108 ,  0.7791709 ,  0.9324073 ,  0.914133  ,
        0.9702964 ,  0.9190478 ,  1.026665  ,  1.02495   ]),
       array([ 0.02364097,  0.04692846,  0.08471032,  0.1534647 ,  0.2157494 ,
        0.2655414 ,  0.3588522 ,  0.4573236 ,  0.6487842 ,  0.6883354 ,
        0.7713876 ,  0.8935084 ,  0.8959837 ,  0.9647381 ,  1.004316  ]),
       array([ 0.01539294,  0.03464131,  0.03679492,  0.1204458 ,  0.1703361 ,
        0.228394  ,  0.296916  ,  0.400557  ,  0.5125622 ,  0.6552897 ,
        0.7982227 ,  0.8336276 ,  0.8567631 ,  0.9399583 ,  0.9836827 ]),
       array([ 0.01177382,  0.06791044,  0.1181224 ,  0.193007  ,  0.2699022 ,
        0.3405689 ,  0.4711433 ,  0.5706022 ,  0.727976  ,  0.7448295 ,
        0.8381671 ,  0.8757077 ,  0.9069215 ,  0.8949114 ]),
       array([ 0.01352529,  0.0307273 ,  0.05200417,  0.08748945,  0.1250032 ,
        0.203918  ,  0.2972467 ,  0.4278211 , 

In [35]:
np.concatenate(WT_09_sat)

array([ 0.04267487,  0.07219977,  0.1823194 ,  0.30881   ,  0.3939354 ,
        0.538879  ,  0.7396108 ,  0.7791709 ,  0.9324073 ,  0.914133  ,
        0.9702964 ,  0.9190478 ,  1.026665  ,  1.02495   ,  0.02364097,
        0.04692846,  0.08471032,  0.1534647 ,  0.2157494 ,  0.2655414 ,
        0.3588522 ,  0.4573236 ,  0.6487842 ,  0.6883354 ,  0.7713876 ,
        0.8935084 ,  0.8959837 ,  0.9647381 ,  1.004316  ,  0.01539294,
        0.03464131,  0.03679492,  0.1204458 ,  0.1703361 ,  0.228394  ,
        0.296916  ,  0.400557  ,  0.5125622 ,  0.6552897 ,  0.7982227 ,
        0.8336276 ,  0.8567631 ,  0.9399583 ,  0.9836827 ,  0.01177382,
        0.06791044,  0.1181224 ,  0.193007  ,  0.2699022 ,  0.3405689 ,
        0.4711433 ,  0.5706022 ,  0.727976  ,  0.7448295 ,  0.8381671 ,
        0.8757077 ,  0.9069215 ,  0.8949114 ,  0.01352529,  0.0307273 ,
        0.05200417,  0.08748945,  0.1250032 ,  0.203918  ,  0.2972467 ,
        0.4278211 ,  0.5314174 ,  0.6516438 ,  0.7035714 ,  0.69

In [36]:
%autoreload

In [37]:
res_wt09 = optimize.least_squares(models.wyman_sp,guess,bounds=bound1,args=(WT_09_lig,WT_09_sat,WT_09_rtot))

ValueError: operands could not be broadcast together with shapes (5,) (72,) 

In [38]:
%autoreload

In [39]:
res_wt09 = optimize.least_squares(models.wyman_sp,guess,bounds=bound1,args=(WT_09_lig,WT_09_sat,WT_09_rtot))

In [49]:
ligs = [ligtools.dilser() for i in range(6)]

In [54]:
np.delete(ligs[0],1)

array([  1.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         6.55360000e+01,   1.31072000e+02])

In [55]:
ligs[0]

array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02])

In [56]:
ligs[0] = np.delete(ligs[0],1)

In [57]:
ligs[0]

array([  1.00000000e-03,   4.00000000e-03,   8.00000000e-03,
         1.60000000e-02,   3.20000000e-02,   6.40000000e-02,
         1.28000000e-01,   2.56000000e-01,   5.12000000e-01,
         1.02400000e+00,   2.04800000e+00,   4.09600000e+00,
         8.19200000e+00,   1.63840000e+01,   3.27680000e+01,
         6.55360000e+01,   1.31072000e+02])

In [87]:
arrarr = np.array(ligs)

In [60]:
ligs2 = [ligtools.dilser() for i in range(6)]

In [64]:
ligs2[0]

array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02])

In [66]:
ligsO = np.asarray(ligs2,dtype='O')

In [69]:
ligsO.shape

(6, 18)

In [72]:
b = np.array(ligs2)

In [77]:
b.flatten().shape

(108,)

In [80]:
ligsO.ravel()

array([0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072,
       0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072,
       0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072,
       0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072,
       0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072,
       0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256,
       0.512, 1.024, 2.048, 4.096, 8.192, 16.384, 32.768, 65.536, 131.072], dtype=object)

In [83]:
b = np.arange(3)

In [84]:
b.shape

(3,)

In [86]:
np.arange(ligs)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [90]:
arrarr.size

6

In [92]:
flatarr = np.concatenate(arrarr)

In [93]:
arrarr*flatarr

ValueError: operands could not be broadcast together with shapes (6,) (107,) 

In [97]:
irreg = np.array([np.array([0,1,2,]),np.array([0,1,2,3])])

In [96]:
things = np.array([1,2])

In [98]:
things*irreg

array([array([0, 1, 2]), array([0, 2, 4, 6])], dtype=object)

In [99]:
np.concatenate(things*irreg)

array([0, 1, 2, 0, 2, 4, 6])

In [107]:
reg = np.array([np.array([0,1,2,3],dtype='O'),np.array([0,1,2,3],dtype='O')],dtype='O')

In [108]:
reg.

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=object)

In [110]:
things.shape

(2,)

In [112]:
reg.shape

(2, 4)

In [117]:
things2 = things[:,np.newaxis]

In [118]:
things2.shape

(2, 1)

In [119]:
things2*reg

array([[0, 1, 2, 3],
       [0, 2, 4, 6]], dtype=object)

In [125]:
WT_09_sat[:,None]*WT_09_rtot[:,None]

array([[ array([  2.51312309e-05,   4.25184446e-05,   1.07367895e-04,
         1.81858209e-04,   2.31988557e-04,   3.17345843e-04,
         4.35556800e-04,   4.58853743e-04,   5.49094659e-04,
         5.38332924e-04,   5.71407550e-04,   5.41227249e-04,
         6.04603018e-04,   6.03593055e-04])],
       [ array([  6.01426277e-05,   1.19386002e-04,   2.15503054e-04,
         3.90414197e-04,   5.48866474e-04,   6.75537322e-04,
         9.12919997e-04,   1.16343124e-03,   1.65050700e-03,
         1.75112526e-03,   1.96241005e-03,   2.27308537e-03,
         2.27938253e-03,   2.45429373e-03,   2.55497990e-03])],
       [ array([  9.89766042e-05,   2.22743623e-04,   2.36591336e-04,
         7.74466494e-04,   1.09526112e-03,   1.46857342e-03,
         1.90916988e-03,   2.57558151e-03,   3.29577495e-03,
         4.21351277e-03,   5.13257196e-03,   5.36022547e-03,
         5.50898673e-03,   6.04393187e-03,   6.32507976e-03])],
       [ array([ 0.0001487 ,  0.00085771,  0.00149189,  0.00243768,

In [128]:
np.concatenate(np.concatenate(WT_09_sat[:,None]*WT_09_rtot[:,None]))

array([  2.51312309e-05,   4.25184446e-05,   1.07367895e-04,
         1.81858209e-04,   2.31988557e-04,   3.17345843e-04,
         4.35556800e-04,   4.58853743e-04,   5.49094659e-04,
         5.38332924e-04,   5.71407550e-04,   5.41227249e-04,
         6.04603018e-04,   6.03593055e-04,   6.01426277e-05,
         1.19386002e-04,   2.15503054e-04,   3.90414197e-04,
         5.48866474e-04,   6.75537322e-04,   9.12919997e-04,
         1.16343124e-03,   1.65050700e-03,   1.75112526e-03,
         1.96241005e-03,   2.27308537e-03,   2.27938253e-03,
         2.45429373e-03,   2.55497990e-03,   9.89766042e-05,
         2.22743623e-04,   2.36591336e-04,   7.74466494e-04,
         1.09526112e-03,   1.46857342e-03,   1.90916988e-03,
         2.57558151e-03,   3.29577495e-03,   4.21351277e-03,
         5.13257196e-03,   5.36022547e-03,   5.50898673e-03,
         6.04393187e-03,   6.32507976e-03,   1.48703347e-04,
         8.57708857e-04,   1.49188591e-03,   2.43767841e-03,
         3.40886479e-03,

In [130]:
3*WT_09_rtot[:,None]

array([[ 0.0017667],
       [ 0.007632 ],
       [ 0.01929  ],
       [ 0.03789  ],
       [ 0.16527  ]])