In [1]:
import matplotlib.pyplot as plt
from scipy import optimize
from mods import prep, plotter
%load_ext autoreload

In [2]:
import sys

In [3]:
sys.path

['',
 '/Users/michael/miniconda3/envs/fitter/lib/python35.zip',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/plat-darwin',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/lib-dynload',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/corner-2.0.1-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/emcee-2.2.1-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg',
 '/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/IPython/extensions',
 '/Users/michael/.ipython']

In [4]:
sys.path.append('/Users/michael/ligbind/')

In [5]:
import ligbind

In [12]:
%autoreload

In [14]:
ligbind.test_helper()

array([  1.00000000e-03,   2.00000000e-03,   4.00000000e-03,
         8.00000000e-03,   1.60000000e-02,   3.20000000e-02,
         6.40000000e-02,   1.28000000e-01,   2.56000000e-01,
         5.12000000e-01,   1.02400000e+00,   2.04800000e+00,
         4.09600000e+00,   8.19200000e+00,   1.63840000e+01,
         3.27680000e+01,   6.55360000e+01,   1.31072000e+02])

In [15]:
WT_08_lbl, WT_08_rtot, WT_08_lig, WT_08_sat = prep.datprep('data/EGFR_WT_08_Sat.csv','data/EGFR_WT_08_Rtot.csv')
WT_09_lbl, WT_09_rtot, WT_09_lig, WT_09_sat = prep.datprep('data/EGFR_WT_09_Sat.csv','data/EGFR_WT_09_Rtot.csv')
WT_11_lbl, WT_11_rtot, WT_11_lig, WT_11_sat = prep.datprep('data/EGFR_WT_11_Sat.csv','data/EGFR_WT_11_Rtot.csv')

hootie hoo! the indices match!
hootie hoo! the indices match!
hootie hoo! the indices match!


In [16]:
import numpy as np

In [17]:
ligbind.test_mod(np.array([5.,2.,0.2,100.]),WT_09_lig,WT_09_rtot)

array([ 0.07355359,  0.13801485,  0.26377134,  0.40632852,  0.54438588,
        0.66491113,  0.77776779,  0.83694946,  0.89840872,  0.92554341,
        0.9526215 ,  0.96771107,  0.97612998,  0.98370091,  0.03896304,
        0.07218896,  0.13609918,  0.24480396,  0.32817271,  0.39463245,
        0.51471551,  0.63346922,  0.75938656,  0.82207472,  0.8892649 ,
        0.92130781,  0.94906444,  0.97439799,  0.98271071,  0.03333476,
        0.06817605,  0.07484841,  0.2161526 ,  0.29158568,  0.35719244,
        0.47036898,  0.59519277,  0.73436921,  0.79638483,  0.8751116 ,
        0.9094885 ,  0.94254595,  0.97087868,  0.98072815,  0.04995212,
        0.07633046,  0.14976527,  0.25266357,  0.38059525,  0.51877965,
        0.66698142,  0.75693923,  0.84701216,  0.89135075,  0.93204039,
        0.95505393,  0.96577702,  0.97731942,  0.0257235 ,  0.05383462,
        0.10354365,  0.15194302,  0.21075995,  0.31184637,  0.42484694,
        0.57061684,  0.67072036,  0.7801341 ,  0.83516995,  0.89

In [45]:
%autoreload

[autoreload of ligbind failed: Traceback (most recent call last):
  File "/Users/michael/miniconda3/envs/fitter/lib/python3.5/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
ImportError: cannot import name 'WymSim'
]


In [8]:
a = ligbind.WymSim(sets=10)

In [9]:
a.meanset

array([[[ 0.00280168,  0.00556532,  0.01056918, ...,  0.99582046,
          0.97955464,  1.01738291],
        [ 0.00246272,  0.00492394,  0.00985403, ...,  1.04032324,
          0.99934072,  0.95897145],
        [ 0.00222463,  0.00444828,  0.00882338, ...,  0.9821678 ,
          0.9605852 ,  0.96855944],
        [ 0.00197007,  0.00401883,  0.00779197, ...,  1.02097728,
          0.993234  ,  0.96968948],
        [ 0.00170204,  0.00326877,  0.00666951, ...,  0.94554617,
          0.95629786,  0.9524222 ],
        [ 0.00154336,  0.00302987,  0.0058747 , ...,  0.98874529,
          0.96127212,  0.98595593]],

       [[ 0.00263089,  0.00524945,  0.01056907, ...,  1.01017801,
          1.0068226 ,  0.99576935],
        [ 0.00242608,  0.00498899,  0.00978171, ...,  0.96166972,
          1.01032423,  1.02155554],
        [ 0.00219275,  0.00428702,  0.00842139, ...,  1.01562974,
          0.97453096,  0.99527201],
        [ 0.00185825,  0.00402008,  0.00795957, ...,  0.98816869,
          0.93

In [ ]:
a.

In [ ]:
a.

In [ ]:
a.

In [ ]:
a.